#!/bin/bash

wget -O vagrantpress-master.zip https://github.com/chad-thompson/vagrantpress/archive/master.zip 
unzip vagrantpress-master.zip 
rm -f vagrantpress-master.zip
mv vagrantpress-master vagrantpress
